### ISSUE TITLE
setuptools.config.pyprojecttoml has no attribute _BetaConfiguration

### ISSUE THREAD

**Issue by geoHeil** [chatnoir-eu/chatnoir-resiliparse#36] opened 2024-01-14 10:56 UTC
```
AttributeError: module 'setuptools.config.pyprojecttoml' has no attribute '_BetaConfiguration'. Did you mean: 'read_configuration'?
```

fails to build in docker on apple silicon.

builds fine on linux and also outside of docker in native osx

```bash
pip install fastwarc==0.14.5
Collecting fastwarc==0.14.5
  Using cached FastWARC-0.14.5.tar.gz (42 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/conda/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/conda/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-jytdl1uv/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-jytdl1uv/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-jytdl1uv/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 34, in <module>
      AttributeError: module 'setuptools.config.pyprojecttoml' has no attribute '_BetaConfiguration'. Did you mean: 'read_configuration'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

**Comment by phoerious** [comment] 2024-01-16 20:49
That looks like a problem with setuptools. Which versions do you have?

**Comment by geoHeil** [comment] 2024-01-16 22:23
- current latest version 69.0.3

**Comment by phoerious** [comment] 2024-04-04 11:52
I've tried, but I cannot reproduce it. tools.setuptools should be there from version 61 and it should be out of _BetaConfiguration by 68 or so. The pyproject.toml requires at least 65. I've tested it with those versions, works fine for me.

I'll close this for now. If this still keeps happening for you, feel free to add more information to this report.

**Closed by phoerious** 2024-04-04 11:52 UTC
Labels: bug
